name = "Ultimate Remastered"
author = "Bedcraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68baef1d14c6e116eaf981b5db2d4c29ada8e82be755bd85d3ed539b422f90a0"

[versions]
forge = "6.6.2.534"
minecraft = "1.4.7"
unsup = "1.2.4"
