name = "Ultimate Remastered"
author = "Bedcraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abfb847ef4098a11f3ccc9d79f8c3ee2b21b524ff283ae6add9d5b72ef9532fd"

[versions]
forge = "6.6.2.534"
minecraft = "1.4.7"
unsup = "1.2.4"
