name = "Ultimate Remastered"
author = "Bedcraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2250d7809467b35c6a6fc6c5485f0e59f273818e21de4a4fa9af2a3d0e8460e2"

[versions]
forge = "6.6.2.534"
minecraft = "1.4.7"
unsup = "1.2.4"
